from distutils.core import setup

setup(
    name='Viewer',
    version='',
    packages=['flask.Lib.site-packages.pbr', 'flask.Lib.site-packages.pbr.cmd', 'flask.Lib.site-packages.pbr.hooks',
              'flask.Lib.site-packages.pbr.tests', 'flask.Lib.site-packages.pbr.tests.testpackage.pbr_testpackage',
              'flask.Lib.site-packages.PIL', 'flask.Lib.site-packages.pip', 'flask.Lib.site-packages.pip.req',
              'flask.Lib.site-packages.pip.vcs', 'flask.Lib.site-packages.pip.utils',
              'flask.Lib.site-packages.pip.compat', 'flask.Lib.site-packages.pip.models',
              'flask.Lib.site-packages.pip._vendor', 'flask.Lib.site-packages.pip._vendor.certifi',
              'flask.Lib.site-packages.pip._vendor.distlib', 'flask.Lib.site-packages.pip._vendor.distlib._backport',
              'flask.Lib.site-packages.pip._vendor.colorama', 'flask.Lib.site-packages.pip._vendor.html5lib',
              'flask.Lib.site-packages.pip._vendor.html5lib.trie',
              'flask.Lib.site-packages.pip._vendor.html5lib.filters',
              'flask.Lib.site-packages.pip._vendor.html5lib.serializer',
              'flask.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'flask.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'flask.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'flask.Lib.site-packages.pip._vendor.lockfile', 'flask.Lib.site-packages.pip._vendor.progress',
              'flask.Lib.site-packages.pip._vendor.requests', 'flask.Lib.site-packages.pip._vendor.requests.packages',
              'flask.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'flask.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'flask.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'flask.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'flask.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'flask.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'flask.Lib.site-packages.pip._vendor.packaging', 'flask.Lib.site-packages.pip._vendor._markerlib',
              'flask.Lib.site-packages.pip._vendor.cachecontrol',
              'flask.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'flask.Lib.site-packages.pip._vendor.pkg_resources', 'flask.Lib.site-packages.pip.commands',
              'flask.Lib.site-packages.pip.operations', 'flask.Lib.site-packages.flask',
              'flask.Lib.site-packages.flask.ext', 'flask.Lib.site-packages.flask.testsuite',
              'flask.Lib.site-packages.flask.testsuite.test_apps.lib.python2.5.site-packages.site_package',
              'flask.Lib.site-packages.flask.testsuite.test_apps.path.installed_package',
              'flask.Lib.site-packages.flask.testsuite.test_apps.flaskext',
              'flask.Lib.site-packages.flask.testsuite.test_apps.flaskext.oldext_package',
              'flask.Lib.site-packages.flask.testsuite.test_apps.moduleapp',
              'flask.Lib.site-packages.flask.testsuite.test_apps.moduleapp.apps',
              'flask.Lib.site-packages.flask.testsuite.test_apps.moduleapp.apps.admin',
              'flask.Lib.site-packages.flask.testsuite.test_apps.moduleapp.apps.frontend',
              'flask.Lib.site-packages.flask.testsuite.test_apps.blueprintapp',
              'flask.Lib.site-packages.flask.testsuite.test_apps.blueprintapp.apps',
              'flask.Lib.site-packages.flask.testsuite.test_apps.blueprintapp.apps.admin',
              'flask.Lib.site-packages.flask.testsuite.test_apps.blueprintapp.apps.frontend',
              'flask.Lib.site-packages.flask.testsuite.test_apps.flask_broken',
              'flask.Lib.site-packages.flask.testsuite.test_apps.config_package_app',
              'flask.Lib.site-packages.flask.testsuite.test_apps.subdomaintestmodule',
              'flask.Lib.site-packages.flask.testsuite.test_apps.flask_newext_package',
              'flask.Lib.site-packages.jinja2', 'flask.Lib.site-packages.jinja2.testsuite',
              'flask.Lib.site-packages.jinja2.testsuite.res', 'flask.Lib.site-packages.migrate',
              'flask.Lib.site-packages.migrate.tests', 'flask.Lib.site-packages.migrate.tests.fixture',
              'flask.Lib.site-packages.migrate.tests.changeset',
              'flask.Lib.site-packages.migrate.tests.changeset.databases',
              'flask.Lib.site-packages.migrate.tests.integrated', 'flask.Lib.site-packages.migrate.tests.versioning',
              'flask.Lib.site-packages.migrate.changeset', 'flask.Lib.site-packages.migrate.changeset.databases',
              'flask.Lib.site-packages.migrate.versioning', 'flask.Lib.site-packages.migrate.versioning.util',
              'flask.Lib.site-packages.migrate.versioning.script',
              'flask.Lib.site-packages.migrate.versioning.templates',
              'flask.Lib.site-packages.migrate.versioning.templates.script',
              'flask.Lib.site-packages.migrate.versioning.templates.repository',
              'flask.Lib.site-packages.migrate.versioning.templates.repository.pylons',
              'flask.Lib.site-packages.migrate.versioning.templates.repository.pylons.versions',
              'flask.Lib.site-packages.migrate.versioning.templates.repository.default',
              'flask.Lib.site-packages.migrate.versioning.templates.repository.default.versions',
              'flask.Lib.site-packages.tempita', 'flask.Lib.site-packages.wtforms',
              'flask.Lib.site-packages.wtforms.ext', 'flask.Lib.site-packages.wtforms.ext.csrf',
              'flask.Lib.site-packages.wtforms.ext.i18n', 'flask.Lib.site-packages.wtforms.ext.django',
              'flask.Lib.site-packages.wtforms.ext.django.templatetags', 'flask.Lib.site-packages.wtforms.ext.dateutil',
              'flask.Lib.site-packages.wtforms.ext.appengine', 'flask.Lib.site-packages.wtforms.ext.sqlalchemy',
              'flask.Lib.site-packages.wtforms.csrf', 'flask.Lib.site-packages.wtforms.fields',
              'flask.Lib.site-packages.wtforms.widgets', 'flask.Lib.site-packages.sqlparse',
              'flask.Lib.site-packages.sqlparse.engine', 'flask.Lib.site-packages.werkzeug',
              'flask.Lib.site-packages.werkzeug.debug', 'flask.Lib.site-packages.werkzeug.contrib',
              'flask.Lib.site-packages.werkzeug.testsuite', 'flask.Lib.site-packages.werkzeug.testsuite.contrib',
              'flask.Lib.site-packages.flask_wtf', 'flask.Lib.site-packages.flask_wtf.recaptcha',
              'flask.Lib.site-packages._markerlib', 'flask.Lib.site-packages.markupsafe',
              'flask.Lib.site-packages.setuptools', 'flask.Lib.site-packages.setuptools.tests',
              'flask.Lib.site-packages.setuptools.command', 'flask.Lib.site-packages.sqlalchemy',
              'flask.Lib.site-packages.sqlalchemy.ext', 'flask.Lib.site-packages.sqlalchemy.ext.declarative',
              'flask.Lib.site-packages.sqlalchemy.orm', 'flask.Lib.site-packages.sqlalchemy.sql',
              'flask.Lib.site-packages.sqlalchemy.util', 'flask.Lib.site-packages.sqlalchemy.event',
              'flask.Lib.site-packages.sqlalchemy.engine', 'flask.Lib.site-packages.sqlalchemy.testing',
              'flask.Lib.site-packages.sqlalchemy.testing.suite', 'flask.Lib.site-packages.sqlalchemy.testing.plugin',
              'flask.Lib.site-packages.sqlalchemy.dialects', 'flask.Lib.site-packages.sqlalchemy.dialects.mssql',
              'flask.Lib.site-packages.sqlalchemy.dialects.mysql', 'flask.Lib.site-packages.sqlalchemy.dialects.oracle',
              'flask.Lib.site-packages.sqlalchemy.dialects.sqlite',
              'flask.Lib.site-packages.sqlalchemy.dialects.sybase',
              'flask.Lib.site-packages.sqlalchemy.dialects.drizzle',
              'flask.Lib.site-packages.sqlalchemy.dialects.firebird',
              'flask.Lib.site-packages.sqlalchemy.dialects.postgresql', 'flask.Lib.site-packages.sqlalchemy.databases',
              'flask.Lib.site-packages.sqlalchemy.connectors', 'flask.Lib.site-packages.flask_testing',
              'flask.Lib.site-packages.pkg_resources', 'flask.Lib.site-packages.pkg_resources._vendor',
              'flask.Lib.site-packages.pkg_resources._vendor.packaging', 'flask.Lib.site-packages.flask_sqlalchemy',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip', 'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip.vcs',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.distlib',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.distlib._backport',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.colorama',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.trie',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.filters',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.serializer',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.treewalkers',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.treeadapters',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.treebuilders',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.chardet',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3.util',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3.contrib',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3.packages',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip._vendor._markerlib',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip.commands',
              'flask.Lib.site-packages.pip-1.5.6-py3.4.egg.pip.backwardcompat', 'Viewer', 'Viewer.scripts',
              'Viewer.db_repository', 'Viewer.db_repository.versions'],
    url='',
    license='',
    author='lolo',
    author_email='',
    description=''
)
